language: node_js
node_js:
  - lts/*
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE roombtest;" -U postgres
  - psql -c "CREATE USER bookertest WITH superuser password '123cde';" -U postgres
  - psql -c "ALTER DATABASE roombtest OWNER TO bookertest;" -U postgres
  - "npm run build:db"

env:
  global:
    - PGPORT=5432
test:
  adapter: postgresql
  database: roombtest

install:
  - npm ci
# keep the npm cache around to speed up installs
cache:
  directories:
    - "$HOME/.npm"
