BEGIN;

DROP TABLE IF EXISTS users , booking , rooms CASCADE;

CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	is_admin BOOLEAN NOT NULL DEFAULT FALSE,
	is_active BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE rooms (
	id SERIAL PRIMARY KEY ,
	name VARCHAR(255) NOT NULL
);

CREATE TABLE booking (
	id SERIAL PRIMARY KEY ,
	room_id INTEGER NOT NULL REFERENCES rooms(id),
	user_id INTEGER NOT NULL REFERENCES users(id),
	start_time TIMESTAMP NOT NULL,
	end_time TIMESTAMP NOT NULL,
	description TEXT NOT NULL
);

COMMIT;
